/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sc.ejemploestudiante.vistas;

import javax.swing.table.DefaultTableModel;
import sc.ejemploestudiante.controladores.ControladorEstudiante;
import sc.ejemploestudiante.modelos.Libro;

/**
 *
 * @author Moises Conde
 */
public class vistaEstudiante extends javax.swing.JFrame {

    private ControladorEstudiante controlador;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(vistaEstudiante.class.getName());
    private DefaultTableModel modeloTabla;

    public vistaEstudiante(ControladorEstudiante controlador) {
        this.controlador = controlador;
        initComponents();
        setLocationRelativeTo(null);
        configurarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLibros = new javax.swing.JTable();
        mostrarLibros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaLibros);

        mostrarLibros.setText("Mostrar Libros");
        mostrarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarLibrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(mostrarLibros)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(mostrarLibros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarLibrosActionPerformed
        cargarLibrosEnTabla();
    }//GEN-LAST:event_mostrarLibrosActionPerformed

    private void cargarLibrosEnTabla() {
        modeloTabla.setRowCount(0);
        Libro[] libros = controlador.obtenerCatalogoLibros();
        for (int i = 0; i < libros.length; i++) {
            Libro libro = libros[i];
            if (libro != null) {
                Object[] fila = {
                    libro.getISBN(),
                    libro.getTitulo(),
                    libro.getAutor(),
                    libro.getEditorial(),
                    libro.getAnioPublicacion(),
                    libro.getCategoria(),
                    libro.getCantidad(),
                    libro.getUbicacion()
                };
                modeloTabla.addRow(fila);

            }
        }
    }

    private void configurarTabla() {
        String[] columnas = {"ISBN", "Título", "Autor", "Editorial", "Año", "Categoría", "Cantidad", "Ubicación"};
        modeloTabla = new DefaultTableModel(columnas, 0);
        tablaLibros.setModel(modeloTabla);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mostrarLibros;
    private javax.swing.JTable tablaLibros;
    // End of variables declaration//GEN-END:variables
}
